services:
  web:
    build: .
    container_name: alx_backend_security
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - alx_backend_security_redis
    env_file:
      - .env

  alx_backend_security_redis:
    image: redis:7-alpine
    container_name: alx_backend_security_redis_cache
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data

volumes:
  redis_data: